apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: bitbucket-runner
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: bitbucket-runner
  app.kubernetes.io/component: cicd
  app.kubernetes.io/part-of: addons
  app.kubernetes.io/managed-by: duplocloud
