apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: circleci-runner
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: circleci-runner
  app.kubernetes.io/component: cicd
  app.kubernetes.io/part-of: addons
  app.kubernetes.io/managed-by: duplocloud
resources:
- repo.yaml
- release.yaml
configMapGenerator:
- name: circleci-runner-values
  files:
  - values.yaml