apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: circleci-runner
spec:
  interval: 5m0s
  releaseName: circleci-runner
  targetNamespace: kube-system
  chart:
    spec: 
      interval: 5m0s
      chart: container-agent
      version: 101.0.8
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: circleci-runner
  set: 
  valuesFrom:
  - kind: ConfigMap
    name: circleci-runner-values
    valuesKey: values.yaml
  - kind: ConfigMap
    name: addon-values
    valuesKey: circleci-runner.yaml
    optional: true
