apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aws-appmesh
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: appmesh
  app.kubernetes.io/component: service-mesh
  app.kubernetes.io/part-of: addons
  app.kubernetes.io/managed-by: duplocloud
resources:
- repo.yaml
- release.yaml
configMapGenerator:
- name: aws-appmesh-values
  files:
  - values.yaml