apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: aws-appmesh
spec:
  interval: 5m0s
  releaseName: aws-appmesh
  targetNamespace: kube-system
  chart:
    spec: 
      interval: 5m0s
      chart: appmesh-controller
      version: 1.12.7
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: aws-appmesh
  set: 
  valuesFrom:
  - kind: ConfigMap
    name: aws-appmesh-values
    valuesKey: values.yaml
  - kind: ConfigMap
    name: addon-values
    valuesKey: aws-appmesh.yaml
    optional: true
