apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aws-efs-csi-driver
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: aws-efs-csi-driver
  app.kubernetes.io/component: storage
  app.kubernetes.io/part-of: addons
  app.kubernetes.io/managed-by: duplocloud
resources:
- repo.yaml
- release.yaml
configMapGenerator:
- name: aws-efs-csi-driver-values
  files:
  - values.yaml