apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aws-lb-controller
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: aws-lb-controller
  app.kubernetes.io/component: networking
  app.kubernetes.io/part-of: addons
  app.kubernetes.io/managed-by: duplocloud
resources:
- repo.yaml
- release.yaml
configMapGenerator:
- name: aws-lb-controller-values
  files:
  - values.yaml