apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: github-actions-controller
namespace: kube-system
commonLabels:
  app.kubernetes.io/name: github-actions-controller
  app.kubernetes.io/component: cicd
  app.kubernetes.io/part-of: addons
  app.kubernetes.io/managed-by: duplocloud
resources:
- repo.yaml
- release.yaml
configMapGenerator:
- name: github-actions-controller-values
  files:
  - values.yaml