apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: github-actions-runner
spec:
  interval: 5m0s
  releaseName: github-actions-runner
  targetNamespace: kube-system
  chart:
    spec: 
      interval: 5m0s
      chart: actions-runner-controller
      version: 0.23.3
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: github-actions-runner
  set: 
  valuesFrom:
    - kind: ConfigMap
      name: github-actions-runner-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: github-actions-runner-overrrides
      valuesKey: values.yaml
      optional: true
