apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
spec:
  interval: 5m0s
  releaseName: rabbitmq-cluster-operator
  targetNamespace: kube-system
  chart:
    spec: 
      interval: 5m0s
      chart: rabbitmq-cluster-operator
      version: 3.7.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rabbitmq-operator
  set: 
  valuesFrom:
    - kind: ConfigMap
      name: rabbitmq-cluster-operator-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: overrrides
      valuesKey: values.yaml
      optional: true
