apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 5m0s
  releaseName: external-dns
  targetNamespace: kube-system
  chart:
    spec: 
      interval: 5m0s
      chart: external-dns
      version: 1.14.4
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: external-dns
  set: 
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: addon-values
      valuesKey: external-dns.yaml
      optional: true
