apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 5m0s
  releaseName: cert-manager
  targetNamespace: kube-system
  chart:
    spec: 
      interval: 5m0s
      chart: cert-manager
      version: v1.11.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  set: 
  valuesFrom:
  - kind: ConfigMap
    name: cert-manager-values
    valuesKey: values.yaml
  - kind: ConfigMap
    name: addon-values
    valuesKey: cert-manager.yaml
    optional: true
